timezone: "Europe/Berlin"
permalink: /:title
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "pages"
    values:
      layout: "default"
